/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.1/userguide/building_java_projects.html
 */

plugins {
	// Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
	id("org.jetbrains.kotlin.jvm") version "1.9.0"
	id("org.jetbrains.compose") version "1.4.3"

	// Apply the application plugin to add support for building a CLI application in Java.
	application
}

repositories {
	// Use Maven Central for resolving dependencies.
	mavenCentral()
	maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
  google()
}

dependencies {
	implementation(compose.desktop.currentOs)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(17))
	}
}

application {
	// Define the main class for the application.
	mainClass.set("nbs2doakmp.AppKt")
}

tasks.jar {
	manifest.attributes["Main-Class"] = "nbs2doakmp.AppKt"
	from(configurations.runtimeClasspath.get().map(::zipTree))
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE;
}
